#ifndef CARD_ID
#define CARD_ID

enum class CardId{
    AMBUSH,
    BAPISM_OF_BLOOD,
    BEASTFORM,
    DASH,
    EXPLOIT,
    FEEDINGFRENZY,
    FEINT,
    LOOK_INTO_MY_EYES,
    MISTFORM,
    PERYUPON,
    RAVENING_SEDUCTION,
    THIRST_FOR_SUSTENANCE,
    ADMINISTER_AID,
    COUNTER_PUNCH,
    DEDUCE_STRATEGY,
    EDUCATION_NEVER_ENDS,
    ELIMINATE_THE_IMPOSSIBLE,
    FIXED_POINT_IN_A_CHANGING_AGE,
    MASTER_OF_DISGUISE,
    SERVICE_REVOLVER,
    STUDY_METHODS,
    THE_GAME_IS_AFOOT,
    CODED_NOTES,
    DREAMIN_OF_REVENGE,
    EMERGE_FROM_MIST,
    IMPOSSIBLE_TO_SEE,
    INTO_THIN_AIR,
    LURKING,
    REIGN_OF_TERROR,
    ROLLING_FOG,
    SLIP_AWAY,
    STEP_LIGHTLY
};
#endif /* CARD_ID */
